// <auto-generated />
using System;
using HRToolAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRToolAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512023649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.Property<Guid>("CandidatesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uuid");

                    b.HasKey("CandidatesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("CandidateSkill");

                    b.HasData(
                        new
                        {
                            CandidatesId = new Guid("a1111111-2222-3333-4444-555555555555"),
                            SkillsId = new Guid("f75853eb-42d6-4bd4-b62e-52aa88667ee3")
                        },
                        new
                        {
                            CandidatesId = new Guid("a1111111-2222-3333-4444-555555555555"),
                            SkillsId = new Guid("c367a281-03d2-426d-8e19-8c2da107295d")
                        },
                        new
                        {
                            CandidatesId = new Guid("b2222222-3333-4444-5555-666666666666"),
                            SkillsId = new Guid("d478b321-12c4-4bd4-a21e-12aa332211aa")
                        });
                });

            modelBuilder.Entity("HRToolAPI.Models.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-2222-3333-4444-555555555555"),
                            DateOfBirth = new DateOnly(1995, 5, 20),
                            Email = "john@example.com",
                            Name = "John Doe",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = new Guid("b2222222-3333-4444-5555-666666666666"),
                            DateOfBirth = new DateOnly(1998, 11, 2),
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            Phone = "987654321"
                        });
                });

            modelBuilder.Entity("HRToolAPI.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f75853eb-42d6-4bd4-b62e-52aa88667ee3"),
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("c367a281-03d2-426d-8e19-8c2da107295d"),
                            Name = ".NET Core"
                        },
                        new
                        {
                            Id = new Guid("d478b321-12c4-4bd4-a21e-12aa332211aa"),
                            Name = "English Language"
                        });
                });

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.HasOne("HRToolAPI.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRToolAPI.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
